export interface SongItemType {
    img: string,
    name: string,
    author: string,
}

export const songs: SongItemType[] = [
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/0.jpg',
        name: '直到世界的尽头',
        author: 'WANDS',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/1.jpg',
        name: '画',
        author: '赵磊',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/2.jpg',
        name: 'Sweet Dreams',
        author: 'TPaul Sax / Eurythmics',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.jpg',
        name: '麝香夫人',
        author: '凤凰传奇',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/4.jpg',
        name: '空心',
        author: '光泽',
    },
     {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/5.jpg',
        name: '反转地球',
        author: '潘玮柏',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/0.jpg',
        name: '直到世界的尽头',
        author: 'WANDS',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/1.jpg',
        name: '画',
        author: '赵磊',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/2.jpg',
        name: 'Sweet Dreams',
        author: 'TPaul Sax / Eurythmics',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.jpg',
        name: '麝香夫人',
        author: '凤凰传奇',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/4.jpg',
        name: '空心',
        author: '光泽',
    },
     {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/5.jpg',
        name: '反转地球',
        author: '潘玮柏',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/0.jpg',
        name: '直到世界的尽头',
        author: 'WANDS',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/1.jpg',
        name: '画',
        author: '赵磊',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/2.jpg',
        name: 'Sweet Dreams',
        author: 'TPaul Sax / Eurythmics',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.jpg',
        name: '麝香夫人',
        author: '凤凰传奇',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/4.jpg',
        name: '空心',
        author: '光泽',
    },
     {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/5.jpg',
        name: '反转地球',
        author: '潘玮柏',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/0.jpg',
        name: '直到世界的尽头',
        author: 'WANDS',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/1.jpg',
        name: '画',
        author: '赵磊',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/2.jpg',
        name: 'Sweet Dreams',
        author: 'TPaul Sax / Eurythmics',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/3.jpg',
        name: '麝香夫人',
        author: '凤凰传奇',
    },
    {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/4.jpg',
        name: '空心',
        author: '光泽',
    },
     {
        img: 'http://yjy-teach-oss.oss-cn-beijing.aliyuncs.com/HeimaCloudMusic/5.jpg',
        name: '反转地球',
        author: '潘玮柏',
    },
]